---
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    rebase-strategy: 'disabled'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'bundler'
    directory: '/'
    rebase-strategy: 'disabled'
    schedule:
      interval: 'daily'
    groups:
      rubocop:
        patterns:
          - 'rubocop'
          - 'rubocop-*'
